"""initial

Revision ID: 0fe582bcee6d
Revises: None
Create Date: 2026-08-04 19:37:05.478807

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import vortex.storage.models

# revision identifiers, used by Alembic.
revision: str = "0fe582bcee6d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("actor_id", vortex.storage.models.UUIDType(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", vortex.storage.models.UUIDType(length=36), nullable=True),
        sa.Column("metadata", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_tenant_created", "audit_log", ["tenant_id", "created_at"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("monthly_budget_usd", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("tenant_id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("rate_limit_rpm", sa.INTEGER(), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index("idx_api_keys_hash", "api_keys", ["key_hash"], unique=False)
    op.create_index("idx_api_keys_tenant", "api_keys", ["tenant_id"], unique=False)
    op.create_table(
        "eval_datasets",
        sa.Column("id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("tenant_id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.INTEGER(), nullable=False),
        sa.Column("items", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompt_templates",
        sa.Column("id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("tenant_id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.INTEGER(), nullable=False),
        sa.Column("template", sa.TEXT(), nullable=False),
        sa.Column("variables", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", "version", name="uq_prompt_tenant_name_version"),
    )
    op.create_table(
        "workflow_definitions",
        sa.Column("id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("tenant_id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.INTEGER(), nullable=False),
        sa.Column("dag", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", "version", name="uq_workflow_tenant_name_version"),
    )
    op.create_index("idx_workflow_defs_tenant", "workflow_definitions", ["tenant_id"], unique=False)
    op.create_table(
        "workflow_runs",
        sa.Column("id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("tenant_id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("definition_id", vortex.storage.models.UUIDType(length=36), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("input", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("output", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("checkpoint", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("total_tokens", sa.INTEGER(), nullable=False),
        sa.Column("total_cost_usd", sa.DECIMAL(precision=10, scale=6), nullable=False),
        sa.Column("max_cost_usd", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["definition_id"], ["workflow_definitions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_run_tenant_idempotency"),
    )
    op.create_index("idx_workflow_runs_heartbeat", "workflow_runs", ["status", "heartbeat_at"], unique=False)
    op.create_index("idx_workflow_runs_tenant_status", "workflow_runs", ["tenant_id", "status"], unique=False)
    op.create_table(
        "eval_results",
        sa.Column("id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("tenant_id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("dataset_id", vortex.storage.models.UUIDType(length=36), nullable=True),
        sa.Column("run_id", vortex.storage.models.UUIDType(length=36), nullable=True),
        sa.Column("scores", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("item_results", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["eval_datasets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["workflow_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "node_runs",
        sa.Column("id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("run_id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=255), nullable=False),
        sa.Column("node_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("input", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("output", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("error", sa.TEXT(), nullable=True),
        sa.Column("retry_count", sa.INTEGER(), nullable=False),
        sa.Column("tokens_in", sa.INTEGER(), nullable=True),
        sa.Column("tokens_out", sa.INTEGER(), nullable=True),
        sa.Column("cost_usd", sa.DECIMAL(precision=10, scale=6), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("cache_hit", sa.BOOLEAN(), nullable=False),
        sa.Column("latency_ms", sa.INTEGER(), nullable=True),
        sa.Column("eval_scores", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("guardrail_results", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_node_runs_run_id", "node_runs", ["run_id"], unique=False)
    op.create_index("idx_node_runs_type_status", "node_runs", ["node_type", "status"], unique=False)
    op.create_table(
        "workflow_events",
        sa.Column("id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("tenant_id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("run_id", vortex.storage.models.UUIDType(length=36), nullable=False),
        sa.Column("sequence_number", sa.INTEGER(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_data", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "sequence_number", name="uq_event_run_seq"),
    )
    op.create_index("idx_events_run_seq", "workflow_events", ["run_id", "sequence_number"], unique=False)
    op.create_index("idx_events_type", "workflow_events", ["event_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_events_type", table_name="workflow_events")
    op.drop_index("idx_events_run_seq", table_name="workflow_events")
    op.drop_table("workflow_events")
    op.drop_index("idx_node_runs_type_status", table_name="node_runs")
    op.drop_index("idx_node_runs_run_id", table_name="node_runs")
    op.drop_table("node_runs")
    op.drop_table("eval_results")
    op.drop_index("idx_workflow_runs_tenant_status", table_name="workflow_runs")
    op.drop_index("idx_workflow_runs_heartbeat", table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index("idx_workflow_defs_tenant", table_name="workflow_definitions")
    op.drop_table("workflow_definitions")
    op.drop_table("prompt_templates")
    op.drop_table("eval_datasets")
    op.drop_index("idx_api_keys_tenant", table_name="api_keys")
    op.drop_index("idx_api_keys_hash", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("tenants")
    op.drop_index("idx_audit_tenant_created", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
